# Generated by Django 5.1.6 on 2025-02-25 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='sentiment',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='suggestion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='mood',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
